/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Det-Pc
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtCedula = new javax.swing.JTextField();
        TxtValCedula = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtContrasenia = new javax.swing.JPasswordField();
        BtnRegistrarse = new javax.swing.JButton();
        BtnIniciarS = new javax.swing.JButton();
        TxtValContrasenia = new javax.swing.JLabel();
        ImgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Cedula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        TxtCedula.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TxtCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        TxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 210, -1));

        TxtValCedula.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        TxtValCedula.setForeground(new java.awt.Color(204, 0, 51));
        TxtValCedula.setText("*Campo obligatorio");
        getContentPane().add(TxtValCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 210, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        TxtContrasenia.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TxtContrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        TxtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtContraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 210, -1));

        BtnRegistrarse.setBackground(new java.awt.Color(0, 102, 204));
        BtnRegistrarse.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BtnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrarse.setText("Registrarse");
        getContentPane().add(BtnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        BtnIniciarS.setBackground(new java.awt.Color(0, 102, 204));
        BtnIniciarS.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BtnIniciarS.setForeground(new java.awt.Color(255, 255, 255));
        BtnIniciarS.setText("Iniciar sesión");
        getContentPane().add(BtnIniciarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        TxtValContrasenia.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        TxtValContrasenia.setForeground(new java.awt.Color(204, 0, 51));
        TxtValContrasenia.setText("*Campo obligatorio");
        getContentPane().add(TxtValContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 210, -1));

        ImgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImgLogin.jpg"))); // NOI18N
        getContentPane().add(ImgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCedulaActionPerformed

    private void TxtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtContraseniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnIniciarS;
    public javax.swing.JButton BtnRegistrarse;
    private javax.swing.JLabel ImgFondo;
    public javax.swing.JTextField TxtCedula;
    public javax.swing.JPasswordField TxtContrasenia;
    public javax.swing.JLabel TxtValCedula;
    public javax.swing.JLabel TxtValContrasenia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
